GET http://localhost:8001/posts

###

GET http://localhost:8001/posts/1

###

POST http://localhost:8001/posts
Content-Type: application/json

{
    "title": "Article 1",
    "content": "Lorem Ipsum"
}

###

PUT http://localhost:8001/posts/3 
Content-Type: application/json

{
    "title": "Article rename 3",
    "content": "Lorem Ipsum 3"
}

###

DELETE http://localhost:8001/posts/1
